BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            multiline: False
            size_hint_x: 0.8
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.2
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: ''

